name: release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+" # e.g. v1.0.0

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  release-android:
    runs-on: ubuntu-latest

    name: 🤖 Release Android

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ☕️ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: 🔐 Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks


      - name: 🔢 Bump build number
        run: |
          NEW_BUILD_NUMBER=$(date +%s)
          sed -i "s/^version: .*$/version: 1.0.0+$NEW_BUILD_NUMBER/" pubspec.yaml

      - name: 🧪 Debug Keystore Info
        run: |
          echo "➡️ Keystore secret length (base64-encoded):"
          echo "${{ secrets.KEYSTORE }}" | wc -c
          echo "➡️ Checking if keystore.jks exists:"
          ls -l ${{ github.workspace }}/keystore.jks || echo "❌ keystore.jks not found"
          echo "➡️ File type of decoded keystore:"
          file ${{ github.workspace }}/keystore.jks || echo "❌ file command failed"
          echo "➡️ First 64 bytes of the keystore (hex view):"
          head -c 64 ${{ github.workspace }}/keystore.jks | hexdump -C || echo "❌ head/hexdump failed"


      - name: 🚀 Shorebird Release
        uses: shorebirdtech/shorebird-release@v0
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        with:
          platform: android
          args: "--verbose --artifact=apk"

      - name: 📦 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter_and_friends-${{ github.ref_name }}.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: 📦 Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: flutter_and_friends-${{ github.ref_name }}.aab
          path: build/app/outputs/bundle/release/app-release.aab
